"""Scaffold a new data-source adapter via the waterfall recipe.

Walks through four checks in order, then generates a stub adapter that
satisfies the ``Source`` ABC. Halts at the first viable shortcut so you
don't write 100 lines when an existing tool already covers the case.

The waterfall (codified from SKILL.md):

    1. Does an existing Python lib wrap this API?
       (yfinance / fredapi / python-binance / openbb-platform / …)
       → if yes, your adapter wraps the lib, ~30 LOC.

    2. Does OpenBB Platform already ship a provider for it?
       openbb-platform supports ~100 free + paid data providers.
       → if yes, your adapter calls openbb.obb.<provider>.<command>, ~30 LOC.

    3. Does the upstream ship an official MCP server?
       Check modelcontextprotocol.io/servers or the vendor's docs.
       → if yes, federate via an MCPSource shim rather than adapting.

    4. None of the above?
       Read the API docs and hand-write a ~100-LOC adapter conforming
       to the Source ABC. Usually LLM-assisted: paste docs + the ABC
       contract, ask Claude to draft.

Usage::

    python scripts/scaffold_source.py mynewapi
    # ...prompts for kind/intervals/auth/etc., then writes:
    #   quant_radar/sources/mynewapi_src.py  (stub adapter)
    #   appends a CATALOG entry to quant_radar/sources/catalog.py
    #   appends "from quant_radar.sources import mynewapi_src" to hydrate.py
    # ...and prints the waterfall checklist to walk through.

The generated file has TODO markers wherever per-source code is needed.
Run ``python scripts/integration_audit.py`` after filling them in — the
audit fails loudly if any ABC method is missing.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from textwrap import dedent

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCES_DIR = REPO_ROOT / "quant_radar" / "sources"
CATALOG_PATH = SOURCES_DIR / "catalog.py"
HYDRATE_PATH = SOURCES_DIR / "hydrate.py"

WATERFALL = dedent("""\
    ┌─────────────────────────────────────────────────────────────────┐
    │ NEW-SOURCE WATERFALL — check in order, stop at the first match. │
    └─────────────────────────────────────────────────────────────────┘

    1. EXISTING PYTHON LIB?
         pip search    {name}
         pypi.org      https://pypi.org/search/?q={name}
       → if a maintained wrapper exists, your fetch() calls it. ~30 LOC.

    2. OPENBB PROVIDER?
         docs.openbb.co/platform/reference/providers
       → if yes, fetch() calls obb.<provider>.<command>(...). ~30 LOC.
         (`pip install openbb` in the container if not already present.)

    3. OFFICIAL MCP SERVER?
         modelcontextprotocol.io/servers
       → if yes, federate: `claude mcp add` it at the user level instead
         of writing an adapter. The agent calls the MCP tools directly.

    4. HAND-WRITTEN ADAPTER (fallback)
       → Read the upstream's API docs. Implement supports/fetch/search/
         describe in the stub below. LLM-assisted is normal — paste docs
         + base_source.Source + a sibling adapter, ask Claude to draft.

    After filling the stub: run `python scripts/integration_audit.py` to
    verify the contract is satisfied.
""")


ADAPTER_TEMPLATE = '''"""{Name} adapter — TODO: one-line summary of the API.

Generated by scripts/scaffold_source.py. Fill in every TODO marker.
"""

from __future__ import annotations

from datetime import datetime
from typing import cast

import pandas as pd

from quant_radar.cache import CacheKey, get_or_fetch
from quant_radar.sources.base import TTL_DAILY_SEC


SOURCE = "{name}"


def _fetch(symbol: str, start: datetime | None, end: datetime | None) -> pd.DataFrame:
    """TODO — actually call the upstream API and return a DataFrame.

    Return shape: ``DatetimeIndex`` named ``timestamp`` + the columns
    declared in this source's catalog ``schema``. Empty DataFrame if no data.
    """
    raise NotImplementedError("scaffold: implement {name} fetch")


def fetch_{name}(
    symbol: str,
    *,
    start: datetime | None = None,
    end: datetime | None = None,
    refresh: bool = False,
) -> pd.DataFrame:
    """Cache-backed public fetch entry point."""
    key = CacheKey(source=SOURCE, kind="TODO", name=symbol, interval="1d")

    def fetcher(start: datetime | None = None, end: datetime | None = None) -> pd.DataFrame:
        return _fetch(symbol, start, end)

    return get_or_fetch(
        key, fetcher, start=start, end=end, refresh=refresh,
        ttl_seconds=TTL_DAILY_SEC,
    )


def search_{name}(query: str, *, limit: int = 20) -> list[dict]:
    """TODO — keyword search. Return [{{"symbol": ..., "longname": ...}}, ...].

    Return [] if the upstream doesn't expose search.
    """
    return []


def describe_{name}(name: str) -> dict | None:
    """TODO — long-form metadata for one symbol. Return None if unsupported."""
    return None


# --- Source-ABC adapter ---------------------------------------------------

from quant_radar.cards.spec import DataRef as _DataRef  # noqa: E402
from quant_radar.sources.base_source import Source, register_source  # noqa: E402
from quant_radar.sources.catalog import CATALOG  # noqa: E402


class _{Name}Source(Source):
    capability = CATALOG[SOURCE]

    def supports(self, ref: _DataRef) -> bool:
        return ref.source == SOURCE and ref.kind == "TODO"  # set the kind

    def fetch(self, ref: _DataRef, *, refresh: bool = False) -> pd.DataFrame:
        return fetch_{name}(
            ref.name, start=ref.start, end=ref.end, refresh=refresh,
        )

    def search(self, query: str, *, limit: int = 20) -> list[dict]:
        return search_{name}(query, limit=limit)

    def describe(self, name: str) -> dict | None:
        return describe_{name}(name)


register_source(_{Name}Source())
'''


CATALOG_ENTRY_TEMPLATE = '''    "{name}": SourceCapability(
        name="{name}",
        kinds=["TODO"],
        intervals=["TODO"],
        history="TODO",
        coverage="TODO",
        auth="TODO",  # "none" | "API key (FOO_API_KEY env var)" | ...
        rate_limit="TODO",
        status="active",
        examples=["TODO_SYMBOL"],
        schema={{"TODO_KIND": ["TODO_COL_1", "TODO_COL_2"]}},
        notes=(
            "TODO — scaffolded by scripts/scaffold_source.py. "
            "Fill in real metadata. Then run scripts/integration_audit.py."
        ),
    ),
'''


def _validate_name(name: str) -> str:
    if not re.fullmatch(r"[a-z][a-z0-9_]*", name):
        sys.exit(
            f"invalid source name {name!r}: must be lowercase letters / digits / "
            "underscores, starting with a letter (e.g. 'polygon', 'alpha_vantage')"
        )
    return name


def _check_existing(name: str) -> None:
    path = SOURCES_DIR / f"{name}_src.py"
    if path.exists():
        sys.exit(
            f"refusing to overwrite existing adapter at {path}\n"
            f"if you want to re-scaffold, delete it first."
        )


def _write_adapter(name: str) -> Path:
    path = SOURCES_DIR / f"{name}_src.py"
    cap_name = name.replace("_", " ").title().replace(" ", "")
    path.write_text(ADAPTER_TEMPLATE.format(name=name, Name=cap_name))
    return path


def _append_catalog_entry(name: str) -> None:
    """Inject the entry just before the closing `}` of CATALOG."""
    text = CATALOG_PATH.read_text()
    if f'"{name}": SourceCapability' in text:
        return
    # Insert before the final "}" that closes the CATALOG dict literal.
    closing = text.rindex("}\n\n\ndef list_sources")
    entry = CATALOG_ENTRY_TEMPLATE.format(name=name)
    new_text = text[:closing] + entry + text[closing:]
    CATALOG_PATH.write_text(new_text)


def _hint_hydrate_import(name: str) -> str:
    """We don't auto-edit hydrate.py — too risky. Print the line to add."""
    return (
        f'add to quant_radar/sources/hydrate.py:\n'
        f'    from quant_radar.sources import {name}_src  # noqa: F401'
    )


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("name", help="source identifier, e.g. 'polygon' or 'alpha_vantage'")
    args = p.parse_args()

    name = _validate_name(args.name)
    _check_existing(name)

    print(WATERFALL.format(name=name))
    print("\nIf you reached step 4 (hand-written), the scaffold below is your starting point.\n")

    adapter_path = _write_adapter(name)
    _append_catalog_entry(name)
    print(f"  wrote {adapter_path.relative_to(REPO_ROOT)}")
    print(f"  appended catalog entry for '{name}'")
    print()
    print(_hint_hydrate_import(name))
    print()
    print("next: fill the TODO markers, then `python scripts/integration_audit.py`.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
